minutesToChoseAClass = 0.2
codesChannelName = "codes"
medKitRoleName = "medKit"
classEmojis = ["🦋", "🖐️", "🛸"]
signUpEmoji = '✅'
playingRoleName = "Players"
activeRoleName = "Active"
signUpChanName = "sign-up"
adminBotCommandChan = "bot-commands"
#medKitToPlayerMessageId = 669673352637448207
