minutesToChoseAClass = 3
classEmojis = ["🦋", "🖐️", "🛸"]
signUpEmoji = '✅'
playingRoleName = "Players"
activeRoleName = "Active"
signUpChanName = "sign-up"
adminBotCommandChan = "bot-commands"
codesChannelName = "codes-and-class-reactions"
medKitRoleName = "Medkit"
medKitToPlayerMessageId = 669847178419896322
